options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build & push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/backend:latest', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/backend:latest']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'backend-service',
           '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/backend:latest',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

  # Build & push frontend image with platform flag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/frontend:latest', './new-frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/frontend:latest']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'frontend-service',
           '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/frontend:latest',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']