services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    restart: always

  new-frontend:
    build: ./new-frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend